Import('env')
Import('specification')
Import('comparator')

import os

dameApp = env.Program(
        'dame',
        Glob( 'appDame/*.d' ),
        LINKFLAGS = [ '-fPIC' ],
        DFLAGS = [ '-Isrc', '-fPIC', '-unittest' ],
        LIBPATH = [ '/lib64', '#/build/src' ],
        LIBS = [
                'specification',
                'comparator',
                'phobos2'
        ],
)

install_bin_dir = os.path.join(ARGUMENTS.get('prefix', '/usr'), 'bin/')
install_man_dir = os.path.join(ARGUMENTS.get('prefix', '/usr'), 'share/man/man1')

Alias ('install', env.Install(install_bin_dir, dameApp))
Alias ('install', env.Install(install_man_dir, File( 'appDame/dame.man' )))
