Import("env")

specification = env.SharedLibrary(
	'specification',
	Glob( 'specification/*.d' ),
	LINKFLAGS = [ '-m64', '-fPIC' ],
	DFLAGS = [ '-fPIC', '-unittest' ],
	LIBPATH = '/lib64',
	DPATH=['.']
)

comparator = env.SharedLibrary(
	'comparator',
	Glob( 'comparator/*.d' ),
	LINKFLAGS = [ '-m64', '-fPIC' ],
	DFLAGS = [ '-fPIC', '-unittest' ],
	LIBPATH = [ '/lib64', '#/build/src' ],
	DPATH= [ '.' ],
	LIBS = [ 'specification' ]
)

Export( 'specification' )
Export( 'comparator' )
